version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test
  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/index.html
    - build/main.js
  discard-paths: yes